name: Manual Release with Automatic Versioning

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Optional: Version tag for the release (e.g., v1.0.0). Leave blank for automatic increment."
        required: false
        default: ""

permissions:
  contents: write
  packages: read

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get Latest Tag
        id: get_latest_tag
        shell: pwsh
        run: |
          # Check if there are any tags in the repository
          $tagsExist = git tag | Measure-Object | Select-Object -ExpandProperty Count
          if ($tagsExist -eq 0) {
            $latestTag = "v0.0.0"
          } else {
            $latestTag = git describe --tags --abbrev=0 2>$null
          }
          Write-Output "Latest tag: $latestTag"
          "latest_tag=$latestTag" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Validate Version Format
        if: github.event.inputs.version != ''
        shell: pwsh
        run: |
          if ("${{ github.event.inputs.version }}" -notmatch '^v\d+\.\d+\.\d+$') {
            Write-Error "Invalid version format. Must be in format 'vX.Y.Z'"
            exit 1
          }

      - name: Calculate New Version
        id: calculate_version
        shell: pwsh
        run: |
          $latestTag = "${{ env.latest_tag }}"
          Write-Output "Debug: latestTag=$latestTag"
          if ("${{ github.event.inputs.version }}" -ne "") {
            $newVersion = "${{ github.event.inputs.version }}"
          } else {
            if ($latestTag -eq "v0.0.0") {
              $newVersion = "v1.0.0"
            } else {
              $parts = $latestTag -replace "v", "" -split "\."
              $major = [int]$parts[0]
              $minor = [int]$parts[1]
              $patch = [int]$parts[2] + 1
              $newVersion = "v$major.$minor.$patch"
            }
          }
          Write-Output "Debug: Calculated newVersion=$newVersion"
          "new_version=$newVersion" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      - name: Debug Environment After Version Calculation
        run: |
          echo "Debugging environment variables"
          echo "latest_tag=${{ env.latest_tag }}"
          echo "new_version=${{ env.new_version }}"

      - name: Generate Changelog
        id: changelog
        shell: pwsh
        run: |
          $previousTag = git describe --tags --abbrev=0 HEAD^ 2>$null
          if ($?) {
            $changelog = git log --pretty=format:"* %s" "$previousTag..HEAD"
          } else {
            $changelog = git log --pretty=format:"* %s"
          }
          $changelog = $changelog -replace "'", "''" -replace "`n", "%0A"
          "CHANGELOG<<EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
          $changelog | Out-File -FilePath $env:GITHUB_ENV -Append
          "EOF" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore Dependencies
        run: dotnet restore ./ValheimLauncher/ValheimLauncher.csproj

      - name: Build Project
        run: dotnet build --configuration Release ./ValheimLauncher/ValheimLauncher.csproj

      - name: Publish Project
        run: dotnet publish ./ValheimLauncher/ValheimLauncher.csproj -c Release -r win10-x64 --self-contained true -o ./publish

      - name: Archive Build Artifacts
        run: Compress-Archive -Path "./publish/*" -DestinationPath "ValheimLauncher.zip"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_version }}
          release_name: "Release ${{ env.new_version }}"
          body: |
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './ValheimLauncher.zip'
          asset_name: 'ValheimLauncher.zip'
          asset_content_type: 'application/zip'

      - name: Push New Tag
        shell: pwsh
        run: |
          try {
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag ${{ env.new_version }}
            git push origin ${{ env.new_version }}
          } catch {
            Write-Error "Failed to create and push tag: $_"
            exit 1
          }
